### ISSUE TITLE
ImportError: cannot import name 'process'

### ISSUE THREAD

**Issue by anthony-tuininga** [marcelotduarte/cx_Freeze#230]
Originally reported by: **zaazbb (Bitbucket: [zaazbb](https://bitbucket.org/zaazbb), GitHub: [zaazbb](https://github.com/zaazbb))**

----------------------------------------

import Process from multiprocessing,  build a exe and run it, met a import error.

```
#!python

from multiprocessing import Process, Pipe, freeze_support

if __name__ == '__main__':
    freeze_support()
    ...
```

----------------------------------------
- Bitbucket: https://bitbucket.org/anthony_tuininga/cx_freeze/issue/230

**Comment by anthony-tuininga** [comment]
*Original comment by* **zaazbb (Bitbucket: [zaazbb](https://bitbucket.org/zaazbb), GitHub: [zaazbb](https://github.com/zaazbb))**:

----------------------------------------

if i import Process from multiprocessing.context,  it runs ok, no import error.

**Comment by anthony-tuininga** [comment]
*Original comment by* **Graham Jones (Bitbucket: [grahamrjuk](https://bitbucket.org/grahamrjuk), GitHub: [grahamrjuk](https://github.com/grahamrjuk))**:

----------------------------------------

Is this the same as #214 ?

**Comment by Siecje** [comment]
I also have this problem with `cx_Freeze==5.0.1` on Windows.

`from multiprocessing.context import Process` does not work.

**Comment by grahamrjuk** [comment]
I have my own (new) solution which works for me at the moment (assuming the detail is the same as in #214). I forked cx_Freeze and pushed a branch named proceess_import:
https://github.com/grahamrjuk/cx_Freeze/tree/process_import

I give no guarantee that it is the right solution.

Since it may not be the best solution I haven't raised a pull-request for it at the moment. Perhaps that is the best way to find out if I am close to a sensible solution.

**Comment by Siecje** [comment]
I think creating a pull-request is a good idea, even if it doesn't get merged.

**Comment by anthony-tuininga** [comment]
The problem is that the multiprocessing package has both Process (class) and process (submodule) but the imp.find_module() function on Windows finds both of them as submodules! I have pushed a change to cx_Freeze that tells it to ignore multiprocessing.Process. You can see more details on pull request #241 .

**Comment by grahamrjuk** [comment]
I knew there would be a better solution than my original go. Thanks for working this out.

**Comment by anthony-tuininga** [comment]
No problem. Thanks for creating the pull request. It was helpful in that it pointed to the problem that was taking place!

**Comment by reike** [comment]
Hi everyone,
I upgraded cx_Freeze to the latest version :
In [1]: import cx_Freeze
In [2]: cx_Freeze.version
Out[2]: 6.0b1

Still, I get the same error :
`  File "C:\Users\HP\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\__init__.py", line 16, in <module>
    from . import context
  File "C:\Users\HP\AppData\Local\Programs\Python\Python36-32\lib\multiprocessing\context.py", line 5, in <module>
    from . import process
ImportError: cannot import name 'process'`

Has the problem actually been fixed ?

Thanks !

**Comment by niecore** [comment]
I think its not fixed. Same actually happens for **multiprocessing.pool**.
